//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperCliente.SuperPoderesService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CargarSuperPoderesResponse", Namespace="http://schemas.datacontract.org/2004/07/SuperServicio")]
    [System.SerializableAttribute()]
    public partial class CargarSuperPoderesResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObtenerSuperPoderesRequest", Namespace="http://schemas.datacontract.org/2004/07/SuperServicio")]
    [System.SerializableAttribute()]
    public partial class ObtenerSuperPoderesRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObtenerSuperPoderesResponse", Namespace="http://schemas.datacontract.org/2004/07/SuperServicio")]
    [System.SerializableAttribute()]
    public partial class ObtenerSuperPoderesResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] PersonasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Personas {
            get {
                return this.PersonasField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonasField, value) != true)) {
                    this.PersonasField = value;
                    this.RaisePropertyChanged("Personas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SuperPoderesService.ICargarSuperPoderes")]
    public interface ICargarSuperPoderes {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargarSuperPoderes/updateSuperPoderes", ReplyAction="http://tempuri.org/ICargarSuperPoderes/updateSuperPoderesResponse")]
        SuperCliente.SuperPoderesService.CargarSuperPoderesResponse updateSuperPoderes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargarSuperPoderes/updateSuperPoderes", ReplyAction="http://tempuri.org/ICargarSuperPoderes/updateSuperPoderesResponse")]
        System.Threading.Tasks.Task<SuperCliente.SuperPoderesService.CargarSuperPoderesResponse> updateSuperPoderesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargarSuperPoderes/getSuperPoderes", ReplyAction="http://tempuri.org/ICargarSuperPoderes/getSuperPoderesResponse")]
        SuperCliente.SuperPoderesService.ObtenerSuperPoderesResponse getSuperPoderes(SuperCliente.SuperPoderesService.ObtenerSuperPoderesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargarSuperPoderes/getSuperPoderes", ReplyAction="http://tempuri.org/ICargarSuperPoderes/getSuperPoderesResponse")]
        System.Threading.Tasks.Task<SuperCliente.SuperPoderesService.ObtenerSuperPoderesResponse> getSuperPoderesAsync(SuperCliente.SuperPoderesService.ObtenerSuperPoderesRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICargarSuperPoderesChannel : SuperCliente.SuperPoderesService.ICargarSuperPoderes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CargarSuperPoderesClient : System.ServiceModel.ClientBase<SuperCliente.SuperPoderesService.ICargarSuperPoderes>, SuperCliente.SuperPoderesService.ICargarSuperPoderes {
        
        public CargarSuperPoderesClient() {
        }
        
        public CargarSuperPoderesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CargarSuperPoderesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CargarSuperPoderesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CargarSuperPoderesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SuperCliente.SuperPoderesService.CargarSuperPoderesResponse updateSuperPoderes() {
            return base.Channel.updateSuperPoderes();
        }
        
        public System.Threading.Tasks.Task<SuperCliente.SuperPoderesService.CargarSuperPoderesResponse> updateSuperPoderesAsync() {
            return base.Channel.updateSuperPoderesAsync();
        }
        
        public SuperCliente.SuperPoderesService.ObtenerSuperPoderesResponse getSuperPoderes(SuperCliente.SuperPoderesService.ObtenerSuperPoderesRequest request) {
            return base.Channel.getSuperPoderes(request);
        }
        
        public System.Threading.Tasks.Task<SuperCliente.SuperPoderesService.ObtenerSuperPoderesResponse> getSuperPoderesAsync(SuperCliente.SuperPoderesService.ObtenerSuperPoderesRequest request) {
            return base.Channel.getSuperPoderesAsync(request);
        }
    }
}
